export const DEFAULT_ARTICLES = [
  {
    id: "article_plastic_ocean",
    title: "Dampak Sampah Plastik di Lautan",
    category: "Laut",
    readTime: "5 menit",
    difficulty: "Easy",
    rarity: "Common",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 15, xp: 15 },
    summary: "Mengapa plastik menjadi ancaman besar bagi ekosistem laut dan rantai makanan.",
    content:
      "Setiap tahun, jutaan ton sampah plastik masuk ke laut. Plastik sulit terurai dan dapat membahayakan penyu, ikan, burung laut, serta rantai makanan manusia.\n\nYang bisa kamu lakukan:\n- Kurangi plastik sekali pakai\n- Bawa tas belanja sendiri\n- Gunakan botol minum reusable\n- Pilah sampah dari rumah\n- Ikut kegiatan bersih-bersih lingkungan",
    isPublished: true,
  },
  {
    id: "article_composting_home",
    title: "Komposting Rumah untuk Pemula",
    category: "Daur Ulang",
    readTime: "7 menit",
    difficulty: "Easy",
    rarity: "Common",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 15, xp: 15 },
    summary: "Langkah sederhana mengolah sampah organik menjadi kompos yang berguna.",
    content:
      "Komposting membantu mengurangi sampah organik dan menghasilkan pupuk alami. Kamu bisa mulai dari ember kecil, sisa sayur, buah, daun kering, dan sedikit tanah.\n\nTips utama:\n- Seimbangkan bahan hijau dan coklat\n- Jaga kelembaban\n- Aduk berkala\n- Hindari daging, minyak, dan susu",
    isPublished: true,
  },
  {
    id: "article_energy_saving",
    title: "Hemat Energi di Rumah",
    category: "Energi",
    readTime: "6 menit",
    difficulty: "Easy",
    rarity: "Common",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 15, xp: 15 },
    summary: "Kebiasaan kecil yang menurunkan konsumsi listrik dan emisi harian.",
    content:
      "Hemat energi mengurangi emisi sekaligus biaya listrik. Matikan lampu saat tidak digunakan, cabut charger, gunakan LED, dan atur AC di suhu wajar.\n\nMulai dari satu ruangan hari ini, lalu jadikan kebiasaan keluarga.",
    isPublished: true,
  },
  {
    id: "article_zero_waste",
    title: "Zero Waste Bukan Harus Sempurna",
    category: "Urban Eco",
    readTime: "8 menit",
    difficulty: "Medium",
    rarity: "Rare",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 18, xp: 18 },
    summary: "Mengenal prinsip refuse, reduce, reuse, recycle, dan rot secara realistis.",
    content:
      "Zero waste bukan berarti langsung sempurna tanpa sampah. Prinsipnya adalah membuat pilihan yang lebih sadar: tolak yang tidak perlu, kurangi konsumsi, gunakan ulang, daur ulang, dan komposkan sampah organik.",
    isPublished: true,
  },
  {
    id: "article_air_clean",
    title: "Udara Bersih di Kota Padat",
    category: "Polusi",
    readTime: "6 menit",
    difficulty: "Medium",
    rarity: "Rare",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 18, xp: 18 },
    summary: "Cara transportasi, ruang hijau, dan energi bersih membantu kualitas udara.",
    content:
      "Polusi udara berasal dari kendaraan, industri, pembakaran sampah, dan pembangkit berbahan fosil. Solusi kota dimulai dari transportasi publik, jalur sepeda, ruang hijau, dan kebiasaan tidak membakar sampah.",
    isPublished: true,
  },
  {
    id: "article_forest_guardian",
    title: "Hutan sebagai Penjaga Iklim",
    category: "Hutan",
    readTime: "7 menit",
    difficulty: "Medium",
    rarity: "Rare",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 18, xp: 18 },
    summary: "Hutan menyimpan karbon, menjaga air, dan menjadi rumah keanekaragaman hayati.",
    content:
      "Hutan menyerap karbon, menjaga siklus air, mencegah erosi, dan menjadi habitat satwa. Melindungi hutan berarti menjaga stabilitas iklim dan kehidupan masyarakat sekitar.",
    isPublished: true,
  },
  {
    id: "article_climate_basics",
    title: "Climate Change dalam Bahasa Sederhana",
    category: "Climate",
    readTime: "8 menit",
    difficulty: "Medium",
    rarity: "Epic",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 20, xp: 20 },
    summary: "Memahami gas rumah kaca, cuaca ekstrem, dan aksi mitigasi harian.",
    content:
      "Perubahan iklim terjadi ketika gas rumah kaca menahan panas berlebih di atmosfer. Dampaknya bisa berupa gelombang panas, banjir, kekeringan, dan perubahan ekosistem. Aksi kecil seperti hemat energi, menanam pohon, dan mengurangi sampah tetap berarti bila dilakukan bersama.",
    isPublished: true,
  },
  {
    id: "article_clean_water",
    title: "Air Bersih dan Sanitasi",
    category: "Air Bersih",
    readTime: "6 menit",
    difficulty: "Easy",
    rarity: "Common",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 15, xp: 15 },
    summary: "Kenapa sungai, sumur, dan drainase harus bebas limbah.",
    content:
      "Air bersih penting untuk kesehatan. Sampah, minyak, deterjen berlebihan, dan limbah kimia dapat merusak sungai dan tanah. Mulai dari tidak membuang sampah ke selokan dan menggunakan produk rumah tangga seperlunya.",
    isPublished: true,
  },
  {
    id: "article_wildlife_protection",
    title: "Melindungi Satwa di Sekitar Kita",
    category: "Satwa",
    readTime: "5 menit",
    difficulty: "Easy",
    rarity: "Common",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 15, xp: 15 },
    summary: "Habitat kecil seperti taman dan sungai bersih membantu satwa lokal bertahan.",
    content:
      "Satwa membutuhkan makanan, air, dan tempat berlindung. Taman dengan tanaman lokal, sungai bersih, dan minim pestisida dapat membantu burung, kupu-kupu, ikan, dan serangga penyerbuk.",
    isPublished: true,
  },
  {
    id: "article_green_tech",
    title: "Green Technology untuk Masa Depan",
    category: "Green Technology",
    readTime: "9 menit",
    difficulty: "Hard",
    rarity: "Epic",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 22, xp: 22 },
    summary: "Panel surya, sensor sampah, bangunan hemat energi, dan kota pintar hijau.",
    content:
      "Green technology membantu manusia hidup lebih efisien tanpa membebani bumi. Contohnya panel surya, lampu pintar, sensor kualitas udara, sistem pemilahan sampah, dan bangunan hemat energi.",
    isPublished: true,
  },
  {
    id: "article_recycle_sorting",
    title: "Panduan Pilah Sampah",
    category: "Daur Ulang",
    readTime: "6 menit",
    difficulty: "Easy",
    rarity: "Common",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 15, xp: 15 },
    summary: "Bedakan plastik, kertas, kaleng, kaca, organik, dan elektronik.",
    content:
      "Pilah sampah dari sumbernya. Plastik, kertas, kaleng, dan kaca lebih mudah didaur ulang jika bersih dan kering. Organik cocok untuk kompos. Baterai dan elektronik perlu tempat khusus karena mengandung bahan berbahaya.",
    isPublished: true,
  },
  {
    id: "article_ocean_microplastic",
    title: "Mikroplastik dan Makanan Laut",
    category: "Laut",
    readTime: "7 menit",
    difficulty: "Hard",
    rarity: "Epic",
    minReadSeconds: 5,
    readingReward: { ecoPoints: 22, xp: 22 },
    summary: "Partikel plastik kecil dapat masuk ke rantai makanan dan sulit dibersihkan.",
    content:
      "Mikroplastik berasal dari pecahan plastik besar, serat pakaian sintetis, dan produk tertentu. Ukurannya kecil sehingga sulit disaring. Mengurangi plastik sekali pakai dan mencuci pakaian dengan bijak dapat membantu.",
    isPublished: true,
  },
];
