export const PROFESSIONAL_ASSET_PACKS = [
  {
    id: "ninja_adventure",
    name: "Ninja Adventure Asset Pack",
    sourceUrl: "https://pixel-boy.itch.io/ninja-adventure-asset-pack",
    license: "CC0",
    bestFor: ["characters", "animals", "tilesets", "ui", "effects", "audio"],
    recommended: true,
    notes:
      "Best single-pack upgrade path for EcoQuest because it includes top-down tilesets, animated characters, UI, effects, animals, and audio.",
  },
  {
    id: "opengameart_outdoor_32",
    name: "Outdoor 32x32 Tileset",
    sourceUrl: "https://opengameart.org/content/outdoor-32x32-tileset",
    license: "CC0",
    bestFor: ["grass", "water", "rocks", "signs", "outdoor"],
    recommended: true,
    notes: "Good legal-clean outdoor base for 32x32 Tiled maps.",
  },
  {
    id: "opengameart_rpg_tileset",
    name: "RPG Tileset",
    sourceUrl: "https://opengameart.org/content/rpg-tileset",
    license: "CC0",
    bestFor: ["classic-rpg", "props", "buildings", "terrain"],
    recommended: false,
    notes: "Useful as supplemental art, but 16x16 scale needs remapping if mixed with 32x32 assets.",
  },
  {
    id: "nature_tilecollection_32",
    name: "Nature Tilecollection 32x32",
    sourceUrl: "https://opengameart.org/content/nature-tilecollection-32x32",
    license: "CC0",
    bestFor: ["farmland", "nature", "sand", "grassland"],
    recommended: false,
    notes: "Useful for garden, beach, and nature variation layers.",
  },
];

export const ECOQUEST_ASSET_SLOTS = {
  map: {
    current: "/assets/pixel/ecoquest-pro/maps/eco_world.json",
    target: "/assets/pixel/professional/maps/eco_world.json",
    tiledLayerContract: [
      "ground",
      "grass_detail",
      "paths",
      "shadows",
      "water",
      "buildings",
      "decorations",
      "top_objects",
      "lighting",
      "collision",
      "areas",
      "trash",
      "npcs",
      "stations",
      "ambient",
      "player_spawn",
    ],
  },
  tiles: {
    current: "/assets/pixel/ecoquest-pro/tilesets/ecoquest_tiles.png",
    target: "/assets/pixel/professional/tilesets/ecoquest_tiles.png",
    requiredTiles: [
      "grass_base",
      "grass_detail",
      "dirt_path",
      "stone_path",
      "sand",
      "water_a",
      "water_b",
      "river_edge",
      "tree_base",
      "tree_top",
      "bush",
      "flowers",
      "rock",
      "fence",
      "bench",
      "lamp",
      "sign",
      "bridge",
      "house",
      "school",
      "eco_center",
      "recycle_station",
      "shadow_soft",
      "light_glow",
      "collision_marker",
    ],
  },
  hero: {
    current: "/assets/pixel/character/hero.png",
    target: "/assets/pixel/professional/characters/hero.png",
    frameWidth: 32,
    frameHeight: 32,
    requiredAnimations: [
      "idle_down",
      "idle_left",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_left",
      "walk_right",
      "walk_up",
      "collect_down",
      "interact_down",
    ],
  },
  npcs: {
    current: "/assets/pixel/ecoquest-pro/sprites/npcs.png",
    target: "/assets/pixel/professional/characters/npcs.png",
    frameWidth: 32,
    frameHeight: 32,
    requiredCharacters: [
      "prof_eco",
      "guru_maya",
      "ranger_adi",
      "nelayan_jaya",
      "lina",
      "park_guard",
      "cleaner_bima",
      "vendor_sari",
      "dr_nara",
    ],
  },
  trash: {
    current: "/assets/pixel/ecoquest-pro/sprites/trash_items.png",
    target: "/assets/pixel/professional/objects/trash_items.png",
    frameWidth: 32,
    frameHeight: 32,
    requiredItems: [
      "plastic_bottle",
      "soda_can",
      "cardboard",
      "crumpled_paper",
      "plastic_bag",
      "glass_bottle",
      "banana_peel",
      "old_tire",
      "styrofoam",
      "fishing_net",
    ],
  },
  stations: {
    current: "/assets/pixel/ecoquest-pro/sprites/stations.png",
    target: "/assets/pixel/professional/objects/stations.png",
    frameWidth: 64,
    frameHeight: 64,
    requiredObjects: ["eco_center_station", "city_tps_station"],
  },
  uiTiles: {
    current: "/assets/pixel/professional/ui/pixel_ui_tiles.png",
    target: "/assets/pixel/professional/ui/pixel_ui_tiles.png",
    sourcePack: "kenney_ui_pack_pixel_adventure",
    requiredFor: ["hud", "dialog", "inventory", "buttons"],
  },
  uiPanel: {
    current: "/assets/pixel/professional/ui/panel_dark.png",
    target: "/assets/pixel/professional/ui/panel_dark.png",
    sourcePack: "kenney_ui_pack_pixel_adventure",
    requiredFor: ["hud_panel", "dialog_panel"],
  },
  uiButton: {
    current: "/assets/pixel/professional/ui/button_dark.png",
    target: "/assets/pixel/professional/ui/button_dark.png",
    sourcePack: "kenney_ui_pack_pixel_adventure",
    requiredFor: ["keyboard_hint", "controls"],
  },
  ambientAudio: {
    current: "/assets/pixel/professional/audio/ambient_forest.mp3",
    target: "/assets/pixel/professional/audio/ambient_forest.mp3",
    sourcePack: "opengameart_forest_ambience",
    requiredFor: ["world_ambience"],
  },
  collectAudio: {
    current: "/assets/pixel/professional/audio/collect.ogg",
    target: "/assets/pixel/professional/audio/collect.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["pickup_reward"],
  },
  interactAudio: {
    current: "/assets/pixel/professional/audio/ui_click.ogg",
    target: "/assets/pixel/professional/audio/ui_click.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["dialog", "ui"],
  },
  recycleAudio: {
    current: "/assets/pixel/professional/audio/recycle.ogg",
    target: "/assets/pixel/professional/audio/recycle.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["recycle_station"],
  },
  errorAudio: {
    current: "/assets/pixel/professional/audio/error.ogg",
    target: "/assets/pixel/professional/audio/error.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["rejected_action"],
  },
  footstepAudio: {
    current: "/assets/pixel/professional/audio/footstep.ogg",
    target: "/assets/pixel/professional/audio/footstep.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["movement"],
  },
  dialogBlipAudio: {
    current: "/assets/pixel/professional/audio/dialog_blip.ogg",
    target: "/assets/pixel/professional/audio/dialog_blip.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["dialog_typewriter"],
  },
  uiHoverAudio: {
    current: "/assets/pixel/professional/audio/ui_hover.ogg",
    target: "/assets/pixel/professional/audio/ui_hover.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["ui_hover"],
  },
  levelUpAudio: {
    current: "/assets/pixel/professional/audio/level_up.ogg",
    target: "/assets/pixel/professional/audio/level_up.ogg",
    sourcePack: "kenney_interface_sounds",
    requiredFor: ["level_up"],
  },
};

export function getAssetSlot(slot) {
  return ECOQUEST_ASSET_SLOTS[slot] || null;
}

export function getRecommendedAssetPack() {
  return PROFESSIONAL_ASSET_PACKS.find((pack) => pack.recommended) || PROFESSIONAL_ASSET_PACKS[0];
}
