"use client";

const ICONS = {
  home: [
    "..oo....",
    ".oggo...",
    "oggggo..",
    "occcco..",
    "ocggco..",
    "ocggco..",
    "oooooo..",
    "........",
  ],
  about: [
    ".oooo...",
    ".occco..",
    ".ococo..",
    ".occco..",
    ".ococo..",
    ".occco..",
    ".oooo...",
    "........",
  ],
  key: [
    ".yyyy...",
    "yooooy..",
    "yoccooyy",
    "yooooyoy",
    ".yyyy.oy",
    ".....ooy",
    ".....yyy",
    "........",
  ],
  scroll: [
    "..oooo..",
    ".occcco.",
    ".ocllco.",
    ".occcco.",
    ".ocllco.",
    ".occcco.",
    "..oooo..",
    "........",
  ],
  leaf: [
    "...oo...",
    "..oggo..",
    ".oggggo.",
    "ogglggo.",
    ".oggggo.",
    "..oggo..",
    "...oo...",
    "........",
  ],
  rpg: [
    "..oooo..",
    ".oggggo.",
    "ogcccggo",
    "ogcocggo",
    "ogcccggo",
    ".oggggo.",
    "..oooo..",
    "........",
  ],
  mission: [
    ".ooooo..",
    ".occco..",
    ".ococo..",
    ".occco..",
    ".ococo..",
    ".occco..",
    ".ooooo..",
    "........",
  ],
  rank: [
    "..yyyy..",
    ".yoooy..",
    "yollloy.",
    ".yoooy..",
    "..yyy...",
    "..oyo...",
    ".ooooo..",
    "........",
  ],
  trophy: [
    ".yyyyy..",
    "yollloy.",
    "yollloy.",
    ".yoooy..",
    "..oyo...",
    ".ooooo..",
    "oyyyyyo.",
    "........",
  ],
  ai: [
    ".ooooo..",
    "occccco.",
    "ocgogco.",
    "occccco.",
    "ocoooco.",
    "occccco.",
    ".oo.oo..",
    "........",
  ],
  robot: [
    "..ooo...",
    ".occco..",
    "ocgogco.",
    "occccco.",
    "ocoocoo.",
    ".occco..",
    ".oo.oo..",
    "........",
  ],
  dashboard: [
    "ooooooo.",
    "occccc.",
    "ocggco.",
    "ocggco.",
    "occccc.",
    "ooooooo.",
    "..ooo...",
    "........",
  ],
  logout: [
    "ooooo...",
    "occco...",
    "occcoyy.",
    "occcoyy.",
    "occco...",
    "ooooo...",
    "..ooo...",
    "........",
  ],
  book: [
    "oooooo..",
    "occcco..",
    "ocllco..",
    "occcco..",
    "ocllco..",
    "occcco..",
    "oooooo..",
    "........",
  ],
  xp: [
    "........",
    "ogggooo.",
    "ogggggo.",
    "oooggoo.",
    "ooggooo.",
    "ogggggo.",
    "ogggooo.",
    "........",
  ],
  level: [
    "...y....",
    "..yyy...",
    ".ygggy..",
    "ygggggy.",
    "..ogo...",
    "..ogo...",
    ".ooooo..",
    "........",
  ],
  warrior: [
    "..oooo..",
    ".olllo..",
    ".ococo..",
    "..ogo...",
    ".oggggo.",
    "ogogogo.",
    "..o.o...",
    "........",
  ],
  quest: [
    ".oooo...",
    "occcco..",
    "ocyyco..",
    "ocyyco..",
    "occcco..",
    ".oggo...",
    ".oooo...",
    "........",
  ],
  eco: [
    "..ggg...",
    ".glllg..",
    "gllclg..",
    "glllg...",
    ".ggg.oo.",
    "..g.oggo",
    "....oo..",
    "........",
  ],
  badge: [
    ".oooo...",
    "oyyyyyo.",
    "oylllyo.",
    "oylylyo.",
    "oylllyo.",
    ".oyyyo..",
    "..o.o...",
    "........",
  ],
  energy: [
    "...y....",
    "..yy....",
    ".yyyo...",
    "..oyy...",
    ".oyyy...",
    ".yy.....",
    "y.......",
    "........",
  ],
  recycle: [
    "..gggo..",
    ".go.ogo.",
    "go...go.",
    "og...og.",
    ".ogo.go.",
    "..ogggo.",
    "........",
    "........",
  ],
  recycleBin: [
    ".ggggg..",
    "gooooog.",
    "gocccog.",
    "gocgcog.",
    "gocccog.",
    "gocccog.",
    ".ggggg..",
    "........",
  ],
  tree: [
    "...g....",
    "..ggg...",
    ".gglgg..",
    "gglllgg.",
    "..ooo...",
    "..ooo...",
    ".ooooo..",
    "........",
  ],
  earth: [
    ".ooooo..",
    "occccco.",
    "ocggcco.",
    "occggco.",
    "occcgco.",
    "occccco.",
    ".ooooo..",
    "........",
  ],
  trash: [
    ".ooooo..",
    "..ooo...",
    ".occco..",
    ".ococo..",
    ".ococo..",
    ".occco..",
    ".ooooo..",
    "........",
  ],
  mail: [
    "oooooo..",
    "occcco..",
    "ocllco..",
    "occcco..",
    "ocllco..",
    "oooooo..",
    "........",
    "........",
  ],
  lock: [
    "..ooo...",
    ".o...o..",
    ".o...o..",
    "oooooo..",
    "ocggco..",
    "ocggco..",
    "oooooo..",
    "........",
  ],
  user: [
    "..ooo...",
    ".olllo..",
    ".ololo..",
    "..ooo...",
    ".oggggo.",
    "ogggggo.",
    "ooooooo.",
    "........",
  ],
  shield: [
    ".ooooo..",
    "ogggggo.",
    "oglllgo.",
    "oglllgo.",
    ".oggggo.",
    "..oggo..",
    "...oo...",
    "........",
  ],
  spark: [
    "...y....",
    "..yyy...",
    "yylyyyy.",
    ".yyyy...",
    "..yyy...",
    ".yy.yy..",
    "y....y..",
    "........",
  ],
  bottle: [
    "..ooo...",
    "..oco...",
    ".occco..",
    ".occco..",
    ".occco..",
    ".occco..",
    ".ooooo..",
    "........",
  ],
  butterfly: [
    "oo...oo.",
    "occooco.",
    "occccco.",
    ".ococo..",
    "occccco.",
    "occooco.",
    "oo...oo.",
    "........",
  ],
};

const TONES = {
  o: "outline",
  c: "cyan",
  g: "green",
  l: "light",
  y: "gold",
};

export default function PixelIcon({ type = "leaf", className = "", title = "" }) {
  const icon = ICONS[type] || ICONS.leaf;

  return (
    <span className={`eq-pixel-icon ${className}`} aria-hidden={title ? undefined : true} title={title}>
      {icon.flatMap((row, y) =>
        row.split("").map((cell, x) => (
          <span
            key={`${x}-${y}`}
            className={`eq-pixel-cell ${cell === "." ? "is-empty" : `is-${TONES[cell] || "outline"}`}`}
          />
        ))
      )}
    </span>
  );
}
